name: frameit_chrome
version: 1.0.0
description: >-
  Embed app store and play store screenshots in device frames.
  Drop in replacement for fastlane frameit.

dependencies:
  meta: '>=1.0.0 <2.0.0'
  args: ^1.6.0
  yaml: ^2.2.1
  logging: '>=0.11.3+2 <1.0.0'
  logging_appenders: ^0.4.2+5
  image: ^2.1.14
  # (Small) utility packages
  quiver: ">=2.0.0 <3.0.0"
  path: ^1.7.0
  json_annotation: ^3.0.1

dev_dependencies:
  pedantic: ^1.9.2
  json_serializable: ^3.4.1
  build_runner: ^1.10.2
  builder_static_text: ^0.0.1+2
